apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sx88t4pqt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sx88t4pqt-java-quarkus-gitops